import React from 'react';

const Router = () => {
    return (
        <div>
            <h2 className='text-sky-800 my-5 text-center text-7xl'>This is root router</h2>
            <p className='text-xl text-gray-700'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique repudiandae suscipit, aut at nostrum quas totam nihil, repellendus vitae eum nobis modi quidem ipsam mollitia dolorem iusto necessitatibus atque veritatis ex. Odit aliquam inventore facilis et sapiente laudantium tempore unde! Blanditiis, animi quos. Eius ratione enim, beatae minima ea et atque adipisci libero neque cumque officia provident eligendi minus excepturi voluptas? Enim a vitae laudantium at nobis veniam dolorum rem mollitia illum aut! Molestias debitis, maxime repellendus praesentium recusandae laboriosam blanditiis molestiae excepturi deleniti in architecto repellat ipsum, quam fugit fuga hic aliquam atque sed itaque ad. Facere rem eius molestias nesciunt quas obcaecati sequi fuga nihil aperiam non praesentium, officia ab harum commodi cumque veniam doloremque tenetur consectetur omnis similique nam accusantium atque eos. Ab vitae optio autem neque quaerat similique est provident officia consequuntur natus suscipit facilis veritatis ipsa, vero perspiciatis obcaecati officiis, maiores in exercitationem cumque! Sint rem exercitationem fugit sequi deleniti iste perferendis animi ab dolor repellat tempore ipsum nisi autem, illo obcaecati, saepe nemo nihil numquam eos est blanditiis cumque fuga nulla ullam! Aut labore doloribus doloremque sit rerum? Delectus deserunt, quos asperiores corrupti quidem quia perferendis hic et praesentium repellendus. Voluptatum exercitationem excepturi et laboriosam, dignissimos a illum ratione deserunt vel explicabo autem amet ipsa laborum commodi sed animi cum repudiandae. Doloremque facere pariatur totam quae vero! Repellat pariatur, alias non asperiores, dolor voluptatum corporis sit est quia obcaecati perspiciatis maiores blanditiis eum magni aspernatur mollitia, quam doloribus quos ipsa eveniet qui excepturi libero. Expedita amet, natus iure, nesciunt odio dolorum minima soluta cupiditate quo laboriosam et! Quibusdam quam totam porro minus quos tempore recusandae aperiam incidunt error tempora nobis temporibus ratione, doloremque unde quisquam natus rerum quo fuga mollitia molestiae officiis. Iure repellat quaerat beatae consequatur voluptates aliquam incidunt voluptatum ex ducimus commodi.</p>
        </div>
    );
};

export default Router;